name: catalog-service

services:
  catalog-service:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      catalog-service-postgres:
        condition: service_healthy
    networks:
      - orderplatform-network

  catalog-service-postgres:
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    volumes:
      - catalog-service-postgres-data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
    networks:
      - orderplatform-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 6

volumes:
  catalog-service-postgres-data:
    name: catalog-service-postgres-data

networks:
  orderplatform-network:
    external: true
    name: orderplatform-network
