name: order-service

services:
  order-service:
    build:
      context: .
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8083:8080"
    depends_on:
      order-service-postgres:
        condition: service_healthy
    networks:
      - orderflow-network

  order-service-postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - order-service-postgres-data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
    networks:
      - orderflow-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U order_user -d orders"]
      interval: 10s
      timeout: 5s
      retries: 6

volumes:
  order-service-postgres-data:
    name: order-service-postgres-data

networks:
  orderflow-network:
    external: true
    name: orderflow-network
