server:
  port: 8084

spring:
  application:
    name: payment-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5436/payments
    username: payment_user
    password: payment_local_password
  kafka:
    bootstrap-servers: localhost:29092
  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
