name: payment-service

services:
  payment-service:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      payment-service-postgres:
        condition: service_healthy
    networks:
      - orderflow-network

  payment-service-postgres:
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    volumes:
      - payment-service-postgres-data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
    networks:
      - orderflow-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 6

volumes:
  payment-service-postgres-data:
    name: payment-service-postgres-data

networks:
  orderflow-network:
    external: true
    name: orderflow-network
