spring:
  application:
    name: checkout-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5434/checkout
    username: checkout_user
    password: checkout_local_password
  kafka:
    bootstrap-servers: localhost:29092
  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
