name: checkout-service

services:
  checkout-service:
    build:
      context: .
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8082:8080"
    depends_on:
      checkout-service-postgres:
        condition: service_healthy
    networks:
      - orderflow-network

  checkout-service-postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: checkout
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - checkout-service-postgres-data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
    networks:
      - orderflow-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U checkout_user -d checkout"]
      interval: 10s
      timeout: 5s
      retries: 6

volumes:
  checkout-service-postgres-data:
    name: checkout-service-postgres-data

networks:
  orderflow-network:
    external: true
    name: orderflow-network
